export enum ELevelAccess {
    "ACADEMY" = "ACADEMY",
    "TOURNAMENT" = "TOURNAMENT",
    "TOURNAMENT_AFTER" = "TOURNAMENT_AFTER",
    "CHALLENGE" = "CHALLENGE",
    "TEACHER" = "TEACHER",
    "TEACHER_FOR_TOURNAMENT" = "TEACHER_FOR_TOURNAMENT",
}
